### ISSUE TITLE
Support for expanding snippet from eglot (lsp)

### ISSUE THREAD

**Issue by idlip** [minad/tempel#101]
I see that eglot needs 'yasnippet' underthehood to complete the snippets from lsp. ([refer](https://github.com/joaotavora/eglot/blob/8b5532dd32b25276c1857508030b207f765ef9b6/eglot.el#L1660))
I found out that there is a package, [eglot-tempel](https://github.com/fejfighter/eglot-tempel) which attempts to translate the snippet form to tempel's understandable format.
Since I don't see this anywhere mentioned, I just wanted to bring this to your (author) attention.

For context, I use all your packages, I was wondering if it was corfu's issue for not completing snippet from lsp, later from matrix, I figured that eglot itself needed yasnippet for it.
So, any input and help regarding this implementation would be beneficial to some when emacs29 gets released!

I'm still a novice with elisp, so I cannot think of contributing yet. But I do love to help the community.

-------

I'm a big fan of your packages, If it wasn't for your packages, I wouldn't have loved emacs!
Thank you for making emacs lovely ;)

**Comment by minad** [comment]
See also https://github.com/fejfighter/eglot-tempel/issues/3

**Comment by idlip** [comment]
Oh I didn't know about lsp-snippet.

I have only tried eglot-tempel once, in my test it did not prompt for second field, it only expanded the template (texts), so its not complete i guess.
Will try both and see sometime.

You can close this for now, or leave it for others to comment.

**Comment by idlip** [comment]
I might be wrong in describing `eglot-tempel` issue, here's an attach of video to describe it.

https://github.com/minad/tempel/assets/117019901/a59da8d6-2393-4ccd-8e8a-3715250801da

**Comment by minad** [comment]
Okay, I close this for now. I am interested if progress is made. I am happy to link to any package which materializes and is released on any of the ELPAs. If you have Tempel-specific questions regarding the implementation, please let me know.

**Comment by fejfighter** [comment]
Sorry @idlip life(tm) has been a little demanding lately so have not had a chance to get to this or https://github.com/fejfighter/eglot-tempel/issues/3 

To add clarity, I wrote eglot-tempel as a rough hack to get argument templates working because I wasn't using yasnippet for anything else and tempel seemed lighter/cleaner, pushed it to github to sync across my own computers and if others found it useful, then even better.

I have put in a request to see this pushed to melpa
@idlip could you open an issue in eglot-tempel, that error is most likely with my pattern matching when building the snippet. I'll need to know what server/language it is, I generally only use clangd in anger
