### ISSUE TITLE
`tempel--beginning` only retrieves the starting point of the first overlay in tempel--active

### ISSUE THREAD

**Issue by Elilif** [minad/tempel#108]
```
(defun tempel--beginning ()
  "Return beginning of template markers."
  (and tempel--active
       (cl-loop for st in tempel--active minimize (overlay-start (caar st)))))

(defun tempel--end ()
  "Return end of template markers."
  (and tempel--active
       (cl-loop for st in tempel--active maximize (overlay-end (caar st)))))
```

IIUC, The function `tempel--beginning` is used to find the smallest starting point among all overlays, but it seems that the current version only retrieves the starting point of the first overlay in `tempel--active`. The same applies to `tempel--end`.

So for templates such as:
```
;; ~/.config/emacs/templates

fundamental-mode ;; Available everywhere

(test (p "test" na) n (s na))
```
`tempel-abort` can't clean the entire template.

The following version works well for me.
```
(defun tempel--beginning ()
  "Return beginning of template markers."
  (and tempel--active
       (cl-loop for st in (caar tempel--active) minimize (overlay-start st))))

(defun tempel--end ()
  "Return end of template markers."
  (and tempel--active
       (cl-loop for st in (caar tempel--active) maximize (overlay-end st))))
```

**Comment by minad** [comment]
Hi, thanks for the report. I think the current implementations of `tempel--beginning` and `tempel--end` are correct, since they iterate over the entire list of active templates. The `caar` of one active template state is the range overlay of the entire expanded template.

https://github.com/minad/tempel/blob/23a233da7dc8ed0e71da6c03be667322a3c0c79a/tempel.el#L410-L414

I suspect that you are observing problems since your template starts and ends with placeholders. This doesn't seem useful, since you can always jump before and after the template and edit there.
