### ISSUE TITLE
Support for ordered placeholder

### ISSUE THREAD

**Issue by traxyax** [minad/tempel#109]
This is a feature of yasnippet. It add the possibility to jump to the next placeholder in certain order.
```
# -*- mode: snippet -*-
# name: try
# key: try
# --
try {
    $0
}
catch (${1:Throwable e}) {
      ${2:System.out.println("Error " + e.getMessage());
      e.printStackTrace();}
}
```
In the example above, if i press `<tab>` the point jump successively to $1, $2 and $0.

**Comment by minad** [comment]
Hi! Thanks for the proposal. In Tempel you can jump between placeholders with `tempel-next` and `tempel-previous`. Tempel doesn't support placeholders with indices, but these are mostly not needed. In your example above $0, $1 and $2 are also given in order. Tempel is based on the Tempo template syntax and I try to keep it restricted to that.

**Comment by traxyax** [comment]
When I expand this snippet, the point is automatically inserted at $1. It skip $0. Then i hit `tab` it jump to $2 and after It jump at $0 at the end.

**Comment by minad** [comment]
Oh okay, I see. Do you think it is significantly better to fill out $1 and $2 before $0? Would it not make sense to write the body first and then decide on the exception? If I recall correctly this feature has been proposed before and I wasn't really convinced by the usefulness of jumping back and forth, also since we would have to introduce a syntax extension on top of the Tempo syntax.

**Comment by traxyax** [comment]
I understand.
