### ISSUE TITLE
prefix to disable `:post` actions

### ISSUE THREAD

**Issue by ispringle** [minad/tempel#115]
I'm working on a number of snippets and hoping to get a few PRs in to improve and add to the tempel-collection. One thing I am stuck on though is the question of whether or not to include `:post` actions.

For example, I write nearly all my src code for work in an org file and tangle it to the final src file that'll be committed. I love the ability to declare an org src block and then open that block in a new buffer with the specified mode. However I also recognize that others probably will either not like this or not always want this. One question that has come up while I'm working on the tempel-collection snippets is that you'd either need to make a hard stance on this "never open a new buffer"/"always open a new buffer" or you'd need to provide two versions of each snippet, one for post-effects and one without.

Another idea I had was if there could be some way to prefix the expansion `C-u` style such that if the expansion is prefixed it'll trigger tempel to skip running the `:post`. So for example if I have the template `(elisp & "#+begin_src emacs-lisp" n> r> n "#+end_src" :post (org-edit-src-code))` and I call it with `M-tab` it will write out the src block and then open a new buffer to edit that block. If however I called `C-u M-tab` it would write the source block but then skip the post-effect.

I'm happy to do the work to get this implemented or contribute to that effort, but I might need some guidance in getting that done.

**Comment by minad** [comment]
Hi, thanks for the suggestion. I am not sure if we should use a prefix argument for this feature, since it feels a bit ad-hoc. We may also want to use the prefix argumen for something else. Furthermore it is not clear when to press `C-u` if you use the Capf via Corfu, if it is even possible.

I suggest that you simply write your templates without post actions. In the case of `org-edit-src-code` you won't save ankey presses. Either you press `C-u` before expansion or you press `C-'` inside the source block. 

If you want to provide both variants you could also try to reuse templates, see the include custom element I defined here: https://github.com/minad/tempel#defining-custom-elements. Personally I am not using tempel-collection, since I find it difficult to develop a coherent set of templates. Instead I maintain a small set of custom templates myself which are tailored to my specific needs, some with and some without post actions.
