### ISSUE TITLE
Tempel doesn't work properly with `electric-pair-mode`

### ISSUE THREAD

**Issue by AkibAzmain** [minad/tempel#116]
When I insert the opening character of any pair handled by `electric-pair-mode` at the end of a field, the field doesn't extend.  It works correctly however if I disable `electric-pair-mode`.

For example, for the template `'("--> " p " <--" q)`, the buffer shows `--> || <--||` (`|` indicates field boundary), but after inserting `(`, the buffer shows `--> ||() <--||`, but it was supposed to be `--> |()| <--||`.

**Comment by minad** [comment]
Thanks for the report. I can confirm the problem and did a little bit of debugging. It seems the problem goes away if I disable the `electric-pair-inhibit-predicate`:

~~~ elisp
(electric-pair-mode 1)
(setq electric-pair-inhibit-predicate #'ignore)
~~~

This is not a Tempel issue since a *predicate* shouldn't have observable and unexpected side effects like preventing the Tempel overlay from being extended. Disabling the predicate is probably undesired, so it makes sense to investigate what's wrong there. There exist multiple different predicates which you could also try.

**Comment by AkibAzmain** [comment]
Thanks!

**Comment by minad** [comment]
Okay, great! Do you think `electric-pair-default-inhibit` should be changed such that no modification takes place? If yes, maybe report an upstream bug?

**Comment by AkibAzmain** [comment]
[Bug#66155](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=66155)
