### ISSUE TITLE
Implement conditions

### ISSUE THREAD

**Issue by minad** [minad/tempel#21]
Maybe for efficiency conditions should not be checked per snippet, but rather for a set of snippets. Currently the only "condition" we support is the derived mode check.

~~~ elisp
org-mode

(key template)
(key template)

org-mode :if (org-in-src-header-p)

(key template)
(key template)
~~~

On the other hand one could also avoid implementing conditions in the template file format and rely on the `tempel-template-sources` hooks instead. The hook should check the context and return the templates which apply. This requires more manual Elisp coding of course.

**Comment by Luis-Henriquez-Perez** [comment]
Condition-based snippets were what I was thinking about I said that the data structure of templates was too mode-centric in our discussion in #8. At that time, if a snippet depended on an abstract condition instead of a specific mode, the user will still have to deal with modes because it is assumed by the data structure.

Note that this was at the time when the data structure was the following, but now it has changed (for the better).

```(MODE1 (TRIGGER1 ELEMENTS1) (TRIGGER2 ELEMENTS2)...MODE2 (TRIGGER1 ELEMENTS1...)```.

> On the other hand one could also avoid implementing conditions in the template file format and rely on the tempel-template-sources hooks instead.

Yeah, I thought this is what you were going for with `tempel-template-sources`. I think the answer to this is an opinion-based judgement call--how valuable is the ability to define snippets in a file? Is it valuable enough to justify the cost of extending the file-template syntax?

To me the answer to how valuable it is is "not very". I think that to continue to extend the template file syntax is a bitter-sweet journey. It might add a spec of convenience, but would require more work, further complicate the code and still the file syntax will never be as robust and flexible as pure elisp. 

This is why I personally don't plan using template files at all (funny considering I wrote a PR for using multiple files :).

**Comment by minad** [comment]
I have to think about this more - how important these features are. I've created the two issues #21 and #22 after talking to @tecosaur, who uses both post-operations and conditions heavily.

**Comment by minad** [comment]
@Luis-Henriquez-Perez I created a PR which implements condition support. It is reasonable simple and it does not preclude implementing your own custom condition logic in your own `tempel-template-sources` hooks.
