### ISSUE TITLE
`tempel-expand` has conflict with `ivy-mode`

### ISSUE THREAD

**Issue by allenryb** [minad/tempel#27]
`tempel-expand` can't expand template name at point if `ivy-mode` is enabled. 

For example, in `elisp-mode`, I input `lambda` and then press `M-x tempel-expand`; nothing will happen except the minibuffer shows `Sole match`. 
But everything goes well if I turn off `ivy-mode`. 

`M-x tempel-complete` works if I just input `lamd`.

**Comment by minad** [comment]
I tested Tempel with these completion UIs:

* Builtin default completion
* Corfu
* Vertico +  `consult-completion-in-region`
* Company

In all cases both `tempel-expand` and `tempel-complete` work as expected. Therefore I suspect that this is not a Tempel issue, but an issue of how Ivy handles the completion `:exit-function` in the case of a sole match. I looked at the Ivy code of `ivy-completion-in-region` and in the case of a sole match, the `:exit-function` is not called. This is not correct since the default completion UI calls the function in this case. See the relevant Ivy code https://github.com/abo-abo/swiper/blob/c97ea72285f2428ed61b519269274d27f2b695f9/ivy.el#L2623-L2627. Please open an issue on the Ivy issue tracker.
