### ISSUE TITLE
Warning (org-element-cache): org-element--cache: Unregistered buffer modifications detected. Resetting.

### ISSUE THREAD

**Issue by patrl** [minad/tempel#28]
Thanks for the excellent package! I've been really enjoying its simplicity relative to yasnippet. I'm currently getting an `org-element-cache` warning whenever I expand a snippet in org-mode (iusing emacs version 29.0.5 and org version 9.5.2) . Full message:

``` emacs-lisp
Warning (org-element-cache): org-element--cache: Unregistered buffer modifications detected. Resetting.
If this warning appears regularly, please report it to Org mode mailing list (M-x org-submit-bug-report).
The buffer is: readme.org
 Current command: (nil 1833 1839)
 Chars modified: 1833
 Buffer modified: 1839
 Backtrace:
"  backtrace-to-string(nil)
  org-element--cache-sync(#<buffer readme.org>)
  apply(org-element--cache-sync #<buffer readme.org>)
  timer-event-handler([t 0 0 599999 nil org-element--cache-sync (#<buffer readme.org>) idle 999999 nil])
"
```

I suspect this is related to `inhibit-modification-hooks` interacting with org-element.

**Comment by minad** [comment]
Uh, I don't know. You may want to ask on the org mailing list about that. In particular since you use a bleeding edge version. I only investigate Emacs 27 and Emacs 28 issues, but not above for now. As far as I can tell, the element cache has been overhauled recently: https://github.com/bzg/org-mode/blame/8f50ea2d69b046be8459aaf8176349adf9b1ef17/lisp/org-element.el#L5888-L5890. I will look into this again as soon as the next Org version is released.

**Comment by minad** [comment]
Generally I don't recommend to use the bleeding edge versions in particular not early in the development cycle as of now. Note that Emacs 28 is still not yet released. Of course using Emacs master makes sense if you want to participate in the development.
