### ISSUE TITLE
Issue with lsp-mode and rust-analyzer

### ISSUE THREAD

**Issue by ryankask** [minad/tempel#32]
Hello. I'm trying to replace yasnippet with tempel. I've run into an issue when inserting snippets when lsp-mode is enabled and rust-analyzer is running. rust-analyzer panics and reports issues with offsets.

I've narrowed the issue down to setting `inhibit-modification-hooks` to `t` in `tempel--insert`. I've tried setting it to nil but that breaks things. Is there a way to avoid setting this but still retain the package's functionality?

I've searched lsp-mode's issues and found one reference where the [maintainer says](https://github.com/emacs-lsp/lsp-mode/issues/3048#issuecomment-899705820) packages shouldn't be inhibiting change hooks but I don't know if that's valid or not. I may be able to advise `tempel-expand` so lsp-mode doesn't send updated the language server when tempel is expanding.

Thanks for your amazing work on Tempel and all your other packages.

**Comment by minad** [comment]
Currently Tempel relies on inhibiting the hooks in order to inhibit its own hooks from running! I guess we could implement this differently. For now, disabling lsp-mode while expanding seems like a good idea. I am not sure how lsp does it for yasnippet, which has some lsp-mode integration. My experiences with lsp-mode are mixed, e.g., lsp-mode auto configures Company which makes the situation more difficult for my Corfu package. I hope that these things improve in the future and that we find ways on how the packages can interact and coexist harmonically.

**Comment by ryankask** [comment]
Thanks for the explanation. I see this is required for the overlay modifications hooks. 

I'm using Corfu now as well and the integration seems to work well (I probably followed your instructions). lsp-mode does [clobber](https://github.com/emacs-lsp/lsp-mode/issues/3340) `completion-at-point-functions` so I had to work around that to get `tempel-expand` back in there.

I'll close this and report back if I'm able to work around this.

**Comment by yyoncho** [comment]
> For now, disabling lsp-mode while expanding seems like a good idea.

The issue is after the expansion - the buffer is simply out of sync. FTR there were several packages with similar issue(e. g. aggressive-indent-mode). The fix is tempel to either remove temporary its hooks or to inhibit them from running.

**Comment by yyoncho** [comment]
https://github.com/Malabarba/aggressive-indent-mode/pull/129

**Comment by ryankask** [comment]
Thank you for the fix!
