### ISSUE TITLE
LSP doesn't properly get notified about changes

### ISSUE THREAD

**Issue by MagicRB** [minad/tempel#34]
I know that tempel must inhibit change hooks to work, but could it send a changed event for the whole region that changes. I'll assume it already does this, because why wouldn't it. So the question is, why does LSP mode freak out. I've no idea how to even begin debugging this. I'll send any logs or traces needed, but I don't know what could help.

**Comment by minad** [comment]
Duplicate #32? Please continue the discussion there. But I don't really consider this a serious Tempel issue. This needs more reasearch to be done to figure out the best approach for lsp integration.

**Comment by MagicRB** [comment]
Ill also dig around in it to see whether there isnt a `reload this region` function. Must be something like that somewhere in there

**Comment by minad** [comment]
> I though that this is separate, disabling the change hook is not imo an issue if we perhaps delete and then type in the modifications tempel wants to make with change hook enabled so thay lsp picks it up in one big chunk.

I am not sure that this is a good approach. I would like to avoid such special handling if possible.

**Comment by MagicRB** [comment]
I agree, im using your packages because they dont have special cases, but in this case, its imo either: dont disable change hook or disable it and then have a special case for lsp

**Comment by minad** [comment]
> I agree, im using your packages because they dont have special cases, but in this case, its imo either: dont disable change hook or disable it and then have a special case for lsp

Yes. It is out of the question to add an lsp-mode special case here. Therefore we can either change the implementation here such that it works better with lsp mode or we wait if things change on the side of lsp. I am driving a wait and see strategy with regards to lsp-mode, since lsp-mode is a large package with many assumptions. I am not saying that this is necessarily wrong. They probably have to make all these assumptions to achieve their goals of a full featured IDE-like experience. However for every single of my packages I've got reports that something doesn't work with lsp. Furthermore lsp also gives special treatment to some other packages like company which makes it a bit harder to configure other UIs like corfu. Therefore I just wait until (or even if) my packages gain some traction. Then it makes more sense to look into integration issues.

**Comment by MagicRB** [comment]
As per #32 i assume my fix is no longer necessary, I'll test it soon.
