### ISSUE TITLE
Restrict movement to current field of template

### ISSUE THREAD

**Issue by MagicRB** [minad/tempel#36]
Could we restrict point movement to the current tempel field? So that you can't arrow out of it. It would make it much harder to get tempel into an invalid state by moving out of and then deleting the template (which breaks tempel). Ill try implementing this with advices Ill open a PR if you want (if i manage to impl it)

**Comment by minad** [comment]
No, I don't want such a restriction. It is okay to move out of template fields.

> (which breaks tempel)

This does not "break" Tempel. This is by design. You should not delete a template, instead you should move before the first or beyond the last field with tempel-previous/tempel-next. Furthermore you can also quit with tempel-done (not bound to a key, but you could bind it in your user config) or delete the template with tempel-abort.

**Comment by minad** [comment]
But I may have an idea on how to handle the issue with template deletion, since this is a common issue.
