### ISSUE TITLE
Incorrect input position in continuous `(p ...)`

### ISSUE THREAD

**Issue by BohongHuang** [minad/tempel#55]
Given the following template: 

``` lisp
(f (p "public ") (p "void ") (p "function") "(" p ") {" n> q n "}" >)
```

The cursor will jump to an incorrect position when attempting to overwrite the prompt:

![Kooha-05-28-2022-21-54-26](https://user-images.githubusercontent.com/11132087/170828744-9a240aaa-3bad-48e1-862e-5316b702647b.gif)

**Comment by minad** [comment]
You can either add space between the fields " " or make the fields a single field "public void".

**Comment by drcxd** [comment]
Hi, I found this problem as well. I am not sure if this an issue of the package or the Tempo library. Sometimes, I just need to use two consecutive `(p ...)` sections. 

For example, I am writing a template for a C++ class. It is like
```
(class "class " (p "ClassName" cname) (p " : public BaseClassName") n>
          "{};" n>)
```
If I have to merge the two sections into one, then I cannot reference them individually. However, they are two different concepts in the language, and it is natural to represent them using different sections.

If I add space between the two sections, then when there is no base class to inherit, there would be an extra white space.

Although I could live with the solution of using one single section, I do think this is an issue which should be fixed. However, if it is an issue of the Tempo library, I suppose you can't help with it. Still, I prefer to know the real reason of the problem.

**Comment by minad** [comment]
@drcxd I don't know how to fix this. The problem is that the modification hooks should catch a field update if the point is directly before or after a field. This makes it hard to support fields which lie directly next to each other. But if you have a fix in the form of a patch, I would be happy to accept it.

https://github.com/minad/tempel/blob/da6bcf80d525afc599360cf2e4cf2c403a0da1a4/tempel.el#L286-L288
