### ISSUE TITLE
"eager" named fields

### ISSUE THREAD

**Issue by qwekjh** [minad/tempel#57]
Let's take `asciibox` as an example:
```
(asciibox "+-" (make-string (length str) ?-) "-+" n
          "| " (s str)                       " |" n
          "+-" (make-string (length str) ?-) "-+" n)
```
- I enter the `str` field.
- I do a `M-x tempel-next`, the cursor moves to the end of the template.
- The template is still active at this point: `bar` is still highlighted.
- I do _another_ `M-x tempel-next`, and the template is done.

Of course, I could append `q` to the template like so:
```
(asciibox "+-" (make-string (length str) ?-) "-+" n
          "| " (s str)                       " |" n
          "+-" (make-string (length str) ?-) "-+" n q)
```
But if I want to place the cursor _right after_ `str`, I can't just put `q` after `str` - it behaves the same as before.

I could add space between the fields (`str` and `q`), but this feels like a workaround more than anything else.

Is there (or should there be) a way to declare `str` as an "eager" field, which quit the containing template when jumped _from_ (using `M-x tempel-next`), as opposed to `q` and `r` which quit the containing template when jumped _to_?

**Comment by minad** [comment]
I see. You want to quit the template when leaving a field instead of when entering it. This means we would need some kind of quit indicator, like `!s` to quit when entering and `s!` to quit when leaving. @fritzgrabo proposed such quit indicators in https://github.com/minad/tempel/pull/44#issuecomment-1115324006.

We could add this if you want to create a PR. However I have two requirements:

1. You have to show a more realistic use case which requires this addition.
2. The addition should not add much complexity. This is of course subjective, but I don't want to bloat this package.

As an alternative we could try to ensure that `s q` works. This would probably be the easier fix, since we would only have to check in `tempel-next` if a quit field comes directly behind the current field.
