### ISSUE TITLE
Expanding an org-mode src block template above another block seems broken

### ISSUE THREAD

**Issue by david-vicente** [minad/tempel#71]
I made a couple of GIFs to show the issue.

Expanding a `quote` block doesn't result in any issue, but a `src` block defined exactly in the same way seems broken:

![src bug](https://user-images.githubusercontent.com/57544666/194604078-9b65a261-7b86-459b-af17-4d4613c41f71.gif)

Here I'm expanding a `src` block with the language already chosen and the result is different from the one in the above GIF.

![el bug](https://user-images.githubusercontent.com/57544666/194604103-b23cae99-6389-4748-b0c7-848f77e555b3.gif)

While the GIFs where recorded using my configuration I also tried to reproduce the problem with a minimal `init.el`:

``` emacs-lisp
(add-to-list 'load-path "~/.emacs.d/straight/build/tempel/")
(require 'tempel)

(setq tempel-path "~/.emacs.d/templates/*")
(setq tempel-trigger-prefix "=")

;; Setup completion at point
(defun tempel-setup-capf ()
  ;; Add the Tempel Capf to `completion-at-point-functions'.
  ;; `tempel-expand' only triggers on exact matches. Alternatively use
  ;; `tempel-complete' if you want to see all matches, but then you
  ;; should also configure `tempel-trigger-prefix', such that Tempel
  ;; does not trigger too often when you don't expect it. NOTE: We add
  ;; `tempel-expand' *before* the main programming mode Capf, such
  ;; that it will be tried first.
  (setq-local completion-at-point-functions
	      (cons #'tempel-complete
		    completion-at-point-functions)))
(add-hook 'prog-mode-hook 'tempel-setup-capf)
(add-hook 'text-mode-hook 'tempel-setup-capf)
(add-hook 'org-mode-hook 'tempel-setup-capf)
```
and the problem persisted.

**Comment by minad** [comment]
Yes, please investigate this further and let me know. It could be a bad interaction of org and tempel but tempel itself isn't necessarily doing anything wrong. It works for quote and it works in fundamental-mode.

**Comment by david-vicente** [comment]
> . Do you observe this in real editing scenarios?

Yep, it is really annoying when editing my `org` literate config file. That is how I found it.

**Comment by david-vicente** [comment]
Removing the `>` from the templates solved it:

``` emacs-lisp
(src "#+begin_src" n r n "#+end_src")
(elisp "#+begin_src emacs-lisp" n r n"#+end_src")
```
I think that the expansion was calling `Org-cicle` which tries to complete at point if there is nothing to cicle. I called `undo` and noticed that tempel introduces the first line of the template, moves to the second, calls `tab` (?), and introduces the final line of the block. The issue was in the `tab` part I guess.

**Comment by ispringle** [comment]
I know this is old but this is an org issue. I am getting this problem every time I write a src block (I write nearly all my code in a literate file and then tangle to src which gets committed, so I'm getting this issue _constantly_). I took apart what tempel is doing and the problem is that when it calls the `indent-according-mode` org-mode sees the fresh `#+begin_src` what tempel just inserted and then it greedily looks for the next `#+end_src` without considering any other `#+begin_src`. So the indent is being called like it's elisp. If you were to type `#+foo` and then `tab` in an elisp buffer it'll do the same thing.

@david-vicente your solution works because it's not calling the tab, which I think it needless at this point in the template anyway. I've created #113 to update the examples. I will also open a PR in the collections repo to ensure those are changed.
