### ISSUE TITLE
Running function on region

### ISSUE THREAD

**Issue by adrianadermon** [minad/tempel#75]
I'm trying to write a template that takes a string like "x y z" and replaces it with "x, y, z". However, I can't get it to work (perhaps it's not possible?). 

This template lets me input a string from the minibuffer, and produces the desired output:
`(commas (p "words" words noinsert) (string-replace " " ", " words))`

But what I really want is to mark an existing string and perform the transformation on it. I had expected the following to work, but it doesn't:
`(commas (r "words" words noinsert) (string-replace " " ", " words))`

Would be grateful for any pointers!

**Comment by minad** [comment]
You could try to do some trickery with buffer-substring, but otherwise this feature isn't supported and not planned. Maybe you can find another solution for your problem.

Since a comprehensive corpus of tempel templates is missing, we cannot really tell which features are needed and should be added. But the general principle is to keep the package minimal and not add anything. You could also try to define your own user-elements.

**Comment by adrianadermon** [comment]
I see, thanks for the quick reply!
