### ISSUE TITLE
> does not indent correctly in .yaml files

### ISSUE THREAD

**Issue by SohMahmood** [minad/tempel#80]
Hey to preface I am really enjoying this package as yasnippet was giving me so many headaches so thank you!

I am trying to create snippets for ansible but am having issues with the indentation in .yaml files. 

So a basic snippet I am trying to create is for the following template:
```
- name: test 
  become: true
```

And I create the following snippet:
```
yaml-mode

(nb "- name: "p n>"become: true")
```

But expanding nb leads to this:
```
- name: test 
    become: true
```
If I manually call `indent-according-to-mode` on `become: true` then it aligns it with `name`. I am not sure why tempel is adding two extra spaces.

**Comment by minad** [comment]
Thanks.

The problem is that indent according to mode is called too early, before the first field has been filled. This leads to the incorrect indentation. You could try to use some default values for the p fields.

I think these n> and > commands are maybe not that useful in Tempel. I've got a few reports because of them. If someone has an idea for a better design I would appreciate it.

**Comment by minad** [comment]
See also #73.

**Comment by SohMahmood** [comment]
Ah i see that makes a lot of sense, 

Using the following snippet I get the desired outcome, just with the placeholder `test` after `name`.
`(nb "- name: "p "test" n>"become: true"n> pq"")`

But very interestingly there is a "hack" that can achieve the above desired template by putting an [empty character](https://emptycharacter.com/) in place of `"test"` and it achieves the same thing but with the desired outcome

```
- name: ‎
  become: true
```
I have tested with yamlint and ansible --syntax-check and even run an ansible playbook with this and it all seems to work.

I don't have any issues with other languages only YAML sooo.....maybe problem solved?
