### ISSUE TITLE
expanding numbers and symbols

### ISSUE THREAD

**Issue by stites** [minad/tempel#81]
Hi! I am trying to come up with a cdlatex-like set of templates for org, but I am noticing that I cannot expand single-characters templates like `("0" "\\emptyset")`,  `(0 "\\emptyset")`, or  `(?0 "\\emptyset")`.  Ideally I would also have templates like  `( "-->" "\\longrightarrow")`

Is this possible in tempel? If so, how would I go about doing this?

**Comment by minad** [comment]
It is possible but you have to use symbols. Evaluate (intern "->") in scratch to obtain the symbol with the special syntax for special characters.

**Comment by stites** [comment]
Thank you!

I noticed that this doesn't work for some symbols and I am wondering if it has something to do with escaping in tempel. For instance:

```emacs-lisp
(\'  "\\prime") ;; works
(^  "\\uparrow"        ) ;; doesn't work, maybe because of some kind of regex escaping?
(\. "\\cdot") (\.\.\. "\\cdots") (_\.\.\. "\\ldots") ;; doesn't work, maybe because of collision?
```

Do you think the escaping in tempel could be a problem? If so I can try to look into it.

**Comment by minad** [comment]
The question is how symbols are escaped in the Elisp reader. Did you check out the Emacs and Elisp manual?

**Comment by TamsynUlthara** [comment]
The problem is with [`thing-at-point--beginning-of-symbol` in `thingatpt.el`](https://github.com/emacs-mirror/emacs/blob/b9ebacf40345977ddf18531cb1ebf0f6c56045ae/lisp/thingatpt.el#L357-L360); it only considers characters in the `w` and `_` syntax classes.

Here's some quick-and-dirty advice I came up with in order to allow `#` in my Tempel abbreviations:

```elisp
(let ((tempel-advice
       (lambda (original-func &rest r)
         (let ((temp-syntax-table (copy-syntax-table (syntax-table))))
           (modify-syntax-entry ?# "_" temp-syntax-table)
           (with-syntax-table temp-syntax-table
             (apply original-func r))))))
  (advice-add #'tempel-complete :around tempel-advice)
  (advice-add #'tempel-expand :around tempel-advice)
  (advice-add #'tempel-insert :around tempel-advice))
```

Now a Tempel definition like `(\# "#+begin_" (s name) n> r> n "#+end_" name)` for Org-Mode works for me.

The example can be modified to suit whatever other symbols you need that aren't in the `w_` syntax classes.
