### ISSUE TITLE
Insert region twice in template

### ISSUE THREAD

**Issue by bram85** [minad/tempel#92]
I'd like to insert an Org link with a template as follows:

```lisp
(ddg "[[ddg:" r "][" r "]]")
```

This will consume the region once, but the template quits at the second `r`.

Actually I'm looking for something that works with a region or prompt:

```lisp
(ddg "[[ddg:" (r "Term:" terms t) terms "][" terms "]]")
```

This works for prompted search terms but when using `tempel-insert` on the region, the second part stays empty.

So I wonder if idea is possible with tempel in the first place.

(the NOINSERT is used to workaround some bug in the org element cache that doesn't cope with referring to named fields).

**Comment by minad** [comment]
Oh, that's a bit of a problem. Regions are treated specially in Tempel. The treatment was inherited from Tempo. The behavior is that Tempel just moves the point behind the region and optionally indents it. This implies that we can have only a single region.

https://github.com/minad/tempel/blob/954e306a9b31e09e90c24fea460490a04068fa1f/tempel.el#L356-L358

Now we could change Tempel somehow such that the region is stored beforehand in a variable and then reinserted. This would fix your first example. But this may come with its own set of complications. I am not sure if it is worth the complications. Your `ddg` link seems a bit unconventional, since why would you repeat the exact same text twice? Why not just write `<ddg:link>`?

The second example would be fixed then too. We could also fix it separately such that the variable `terms` is initialized in any case. The current behavior is again inherited by Tempo. The variable is only created when region is obtained from a prompt and not directly from the region.

**Comment by bram85** [comment]
I worked around it with an advice and introducing my own element, the solution can be found [here](https://apps.bram85.nl/git/bram/gists/src/commit/368fbc0d7818b19e841062cc458e73cc8bf3a823/gists/tempel-org-links.el). This not-so-nice code behaves as I'd like it.

Actually I was not aware of the single angle bracket syntax, however, that requires a different variable to be modified to recognize different link types. Also, the prefix of the link type is still visible, which is a bit distracting in certain contexts.

So I consider the issue to be solved, no need to adapt the tempel code.
